translateapp/app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
        path('jobs', views.jobs_index, name="jobs"),
        path('jobs/new', views.new_job, name="new_job"),
        path('jobs/<int:job_id>', views.job_detail, name="job_detail"),
        path('jobs/<int:job_id>/bid', views.bid, name="bid"),
        path('bids/<int:bid_id>/accept', views.accept_bid, name="accept_bid"),
        path('bids/<int:bid_id>/deliver', views.deliver_translation, name="deliver_translation"),
        path('bids/<int:bid_id>', views.bid_detail, name="bid_detail"),
        path('bids/<int:bid_id>/rating', views.rate_bid, name="rate_bid"),
        path('bids/<int:bid_id>/dispute', views.raise_dispute, name="dispute"),
]

translateapp/messanger/urls.py
from django.urls import path
from . import views

app_name = "messanger"
urlpatterns = [
    path('', views.messanger, name="messanger"),
    path('open_chat/<int:user_id>', views.open_chat, name="open_chat"),
    path('send_mess/<int:user_id>', views.send_mess, name="send_mess"),
]

translateapp/translateapp/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home_path'),
    path('app/', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('messanger/', include('messanger.urls'))
]

translateapp/messanger/models.py
from django.db import models

# Create your models here.

translateapp/messanger/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from app.models import Job, Bid, Dispute, Message, Rating
from app.forms import JobForm, BidForm, TranslationForm, DisputeForm, MessageForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# Create your views here.
@login_required
def messanger(request):
    users_w_m = request.user.account.get_users_with_last_m()
    context = {
        'users':users_w_m,
        'messages': None,
        'send_to':None,
    }
    return render(request, 'messanger/messanger.html', context)

@login_required
def open_chat(request, user_id):
    send_to = get_object_or_404(User, pk=user_id)
    users_w_m = request.user.account.get_users_with_last_m()
    messages = request.user.account.get_messages_for_user(user_id)
    context = {
        'users':users_w_m,
        'messages':messages,
        'send_to':send_to,
        'form':MessageForm()
    }
    return render(request, 'messanger/messanger.html', context)
    
@login_required
def send_mess(request, user_id):
    if request.method == 'POST':
        send_to = get_object_or_404(User, pk=user_id)
        form = MessageForm(request.POST)
        if form.is_valid():
            message = Message(
                sender = request.user,
                receiver = send_to,
                text = form.cleaned_data['text']
            )
            message.save()
            return HttpResponseRedirect(reverse('messanger:open_chat', args=(send_to.id,)))
        else:
            users_w_m = request.user.account.get_users_with_last_m()
            messages = request.user.account.get_messages_for_user(user_id)
            context = {
                'users':users_w_m,
                'messages':messages,
                'send_to':send_to,
                'form':form
            }
            return render(request, 'messanger/messanger.html', context)

translateapp/messanger/templates/messanger/messanger.html
{% extends 'app/base.html' %}

{% load widget_tweaks %}

{% block content %}
<div class="container mt-5 h-75">
    <div class="row border border-primary">
        <div class="col-2" style="overflow:scroll;">>
            
            {% for usr, l_m in users %}
                <a href="{% url 'messanger:open_chat' usr.id %}">
                    <div class="card">
                        <p>{{usr.account.name}}</p>
                        <p>{{l_m}}</p>
                    </div>
                </a>
            {% endfor %}
                
        </div>
        <div 
            class="col-10 border border-primary d-flex flex-column"
            style="overflow:scroll;">
            
            {% if send_to %}
                <h3 class="align-self-center">Messages with {{send_to.account.name}}</h3>
            {% endif %}
                
            {% for message in  messages %}
                <div 
                    class="col-6 
                        {% if message.sender == user %}
                            align-self-end
                            border
                            border-success
                        {% else %}
                            align-self-start
                            border
                            border-primary
                        {% endif %}
                        text-wrap
                    ">
                    <p>{{message.sent_at}}</p>
                    <p>{{message.text}}</p>
                </div>
            {% endfor %}
                
            {% if send_to %}
                <form action="{% url 'messanger:send_mess' send_to.id %}" method="post" >
                    {% csrf_token %}
                    <div class="d-flex">
                    {{form.text|add_class:'form-control'}}
                    {% for error in form.text.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    <button type="submit" class="btn custom-btn mt-4">Submit</button>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}